name: Code Quality and Test on PR

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Shallow clone for efficiency

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install Root Dependencies
        run: npm ci
        working-directory: .

      - name: Install App Dependencies
        run: npm ci
        working-directory: app

      - name: Execute ESLint
        run: npm run eslint:report || true
        working-directory: .

      - name: Execute Tests
        run: npm run test:report
        working-directory: app
        continue-on-error: true  # Allows workflow to continue even if tests fail

      - name: Upload ESLint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: report/lint-report.txt

      - name: Upload Readable Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: readable-test-report
          path: app/reports/test-report.txt

      - name: Set ESLint Report Message
        id: set_eslint_report_message
        if: always()
        run: |
          if [ -f "report/lint-report.txt" ]; then
            if [ -s "report/lint-report.txt" ]; then
              echo "message<<EOF" >> $GITHUB_OUTPUT
              cat report/lint-report.txt
              echo "EOF" >> $GITHUB_OUTPUT
            else
              echo "message=No lint errors found." >> $GITHUB_OUTPUT
            fi
          else
            echo "message=No ESLint report found." >> $GITHUB_OUTPUT
          fi

      - name: Comment PR with ESLint Report
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: "ESLint Report"
          message: |
            ```diff
            ${{ steps.set_eslint_report_message.outputs.message }}
            ```

      - name: Set Test Report Message
        id: set_test_report_message
        if: always()
        run: |
          if [ -f "app/reports/test-report.txt" ]; then
            echo "message<<EOF" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "message=Tests have failed or no test report found. Please check the artifacts for more details." >> $GITHUB_OUTPUT
          fi

      - name: Comment PR with Test Report
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: "Test Report"
          message: |
            ```diff
            ${{ steps.set_test_report_message.outputs.message }}
            ```
            ${{ steps.set_test_report_message.outputs.html_link }}