name: Code Quality and Test on PR

on:
  pull_request:
    branches: [ develop ]
    types: [ opened, synchronize, reopened ]

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: CryptoMonitorASW-SPE/template-for-project-TS
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1

      - name: Install Dependencies
        run: npm install
        working-directory: app

      - name: Execute ESLint
        run: npm run eslint:report || true
        working-directory: app

      - name: Execute Tests
        if: env.tests_exist == 'true'
        run: npm run test:report
        working-directory: app

      - name: Upload ESLint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: report/lint-report.txt

      - name: Upload Readable Test Report
        if: env.tests_exist == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: readable-test-report
          path: reports/test-report.txt

      - name: Set ESLint Report Message
        id: set_eslint_report_message
        run: |
          if [ -f "report/lint-report.txt" ]; then
            if [ -s "report/lint-report.txt" ]; then
              echo "message<<EOF" >> $GITHUB_OUTPUT
              cat report/lint-report.txt
              echo "EOF" >> $GITHUB_OUTPUT
            else
              echo "message=No lint errors found." >> $GITHUB_OUTPUT
            fi
          else
            echo "message=No ESLint report found." >> $GITHUB_OUTPUT
          fi

      - name: Comment PR with ESLint Report
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: "ESLint Report"
          message: |
            ```diff
            ${{ steps.set_eslint_report_message.outputs.message }}
            ```

      - name: Set Test Report Message
        id: set_test_report_message
        run: |
          if [ "${{ env.tests_exist }}" == "true" ]; then
            if [ -f "reports/test-report.txt" ]; then
              echo "message<<EOF" >> $GITHUB_OUTPUT
              cat reports/test-report.txt
              echo "EOF" >> $GITHUB_OUTPUT
              echo "html_link=• [View Detailed Test Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_OUTPUT
            else
              echo "message=Tests have failed. Please check the artifacts for more details." >> $GITHUB_OUTPUT
              echo "html_link=• [View Detailed Test Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_OUTPUT
            fi
          else
            echo "message=No tests found." >> $GITHUB_OUTPUT
            echo "html_link=" >> $GITHUB_OUTPUT
          fi

      - name: Comment PR with Test Report
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: "Test Report"
          message: |
            ```diff
            ${{ steps.set_test_report_message.outputs.message }}
            ```
            ${{ steps.set_test_report_message.outputs.html_link }}