name: Code Quality and Test on PR

on:
  pull_request:
    branches: develop
    types: [ opened, synchronize, reopened ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'

      - name: Install Root Dependencies
        run: npm install

      - name: Execute ESLint
        run: npm run eslint > lint-report.txt || true

      - name: Execute Tests (Mochawesome)
        run: npm test:report
        working-directory: app

      - name: Upload ESLint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: report/lint-report.txt

      - name: Upload Mochawesome HTML
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: app/reports/test-report.html

      - name: Comment PR with ESLint Report
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: "ESLint Report"
          message: |
            ```diff
            $(cat lint-report.txt)
            ```

      - name: Comment PR with Test Report Link
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: "Test Report"
          message: |
            Your tests have failed. Download or view the HTML artifact:
            • “test-report.html” in the “Actions” → “Artifacts” of this PR.